方式一：try [[catch]] [[finally]] 真正的将异常处理掉了。

方式二：在方法声明处 throws + 异常类型。指明该方法可能抛出的异常类型。
一旦方法体执行时，出现异常，会在异常代码处生成一个异常累的对象，此对象满足throws后的异常类型是，就会被抛出。后续的代码不在执行。没有处理，只是抛给了方法的调用者。

**如何选用**
如果方法之间是层层递进，相互依赖，那么可以使用throws 
如果是子类继承父类，父类又没有抛出异常，那么可以try catch